// Generated by zotero-plugin-scaffold
/* prettier-ignore */
/* eslint-disable */
// @ts-nocheck

// prettier-ignore
declare namespace _ZoteroTypes {
  interface Prefs {
    PluginPrefsMap: {
      "enable": boolean;
      "configuration": string;
      "debugmode": string;
      "sourcedir": string;
      "filefilterstrategy": string;
      "filepattern": string;
      "matchstrategy": string;
      "bbtyamlkeyword": string;
      "bbtregexp": string;
      "zotkeyregexp": string;
      "mdeditor": string;
      "obsidianvaultname": string;
      "obsidianresolvewithfile": string;
      "logseqgraph": string;
      "logseqprefix": string;
      "grouplibraries": string;
      "removetags": string;
      "tagstr": string;
    };
  }
}
